import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next App PUNK API</title>
        <meta
          name="description"
          content="Generated by create next app and create PUNK API"
        />
      </Head>
      <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus
        magni, architecto molestias praesentium cum deleniti laborum deserunt
        obcaecati, placeat nesciunt beatae optio eius doloremque fugit est sed
        amet commodi quisquam illo rem ipsam? Fuga perferendis molestiae cum
        incidunt, optio iusto dignissimos sapiente atque dolorum aut ipsa
        provident dolore animi fugiat! Porro libero et reiciendis amet! Eligendi
        possimus ratione tempora ipsam magni, ab totam dolor reiciendis nobis
        distinctio amet temporibus eum aut tenetur impedit. Officiis
        accusantium, accusamus rerum dolorum exercitationem magni nam, saepe
        impedit consequatur qui dolorem illum, nihil vitae aperiam consectetur
        ipsum voluptatem quia. Beatae dignissimos error, quibusdam obcaecati
        quasi sed tenetur? Tempora tenetur consectetur delectus itaque sequi
        labore amet nam perspiciatis deserunt! Totam quibusdam ratione ea
        placeat quam facere reprehenderit deserunt provident corrupti obcaecati
        id aspernatur temporibus possimus odio nam sed cum quia iste, sit sint
        ipsa, quae mollitia rem? Deleniti animi dolore laudantium sequi itaque
        voluptatem, fugiat nisi!
      </div>
    </div>
  );
};

export default Home;
