import { useRouter } from "next/router";
import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { BeerCard } from "@/app/components/card";
import { useGetBeersQuery } from "@/app/store/beer/beer.api";
import { Spinner } from "@/app/components/spinner";
import { Header } from "@/app/components/Header";
import { FetchError } from "@/app/components/FetchError";
import { Pagination } from "@/app/components/pagination";

import styles from "@/styles/home.module.scss";

function scrollTop() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}

const Home: NextPage = () => {
  const { data, isLoading, isError } = useGetBeersQuery({});

  if (isLoading) return <Spinner />;
  if (isError) return <FetchError />;
  return (
    <>
      <Head>
        <title>PUNK API | Home</title>
        <meta
          name="description"
          content="Generated by create next app and create PUNK API"
        />
      </Head>

      <Header />

      <div className={styles.container}>
        {data?.map((beer) => (
          <BeerCard key={beer.name} {...beer} />
        ))}
      </div>
    </>
  );
};

export default Home;
